import type { Card, CategoryId, Category } from './types'

// Semua konten kartu ada di file ini. Nambah kartu = tambah string ke array.
// Syarat kata yang bagus: bisa ditebak lewat clue verbal tanpa nyebut katanya.
// Kata nggak boleh kembar DI DALAM satu kategori. Kembar lintas kategori boleh
// (mis. "Palu" si perkakas dan "Palu" si kota) — jawaban penebak sama-sama benar.
export const CATEGORIES: Category[] = [
  {
    id: 'benda',
    label: 'Benda Sehari-hari',
    words: [
      'Pasta Gigi', 'Sikat Gigi', 'Sabun Mandi', 'Sampo', 'Handuk',
      'Ember', 'Gayung', 'Sapu', 'Pel Lantai', 'Kemoceng',
      'Tempat Sampah', 'Sikat Kamar Mandi', 'Cermin', 'Sisir', 'Gunting Kuku',
      'Pisau Cukur', 'Tisu Toilet', 'Keran Air', 'Bak Mandi', 'Kloset',
      'Panci', 'Wajan', 'Spatula', 'Sendok', 'Garpu',
      'Pisau Dapur', 'Talenan', 'Piring', 'Mangkuk', 'Gelas',
      'Cangkir', 'Teko', 'Sedotan', 'Kompor Gas', 'Tabung Gas',
      'Rice Cooker', 'Kulkas', 'Blender', 'Oven', 'Microwave',
      'Dispenser Air', 'Termos', 'Toples', 'Saringan Teh', 'Parutan Keju',
      'Ulekan', 'Cobek', 'Serbet', 'Tudung Saji', 'Rak Piring',
      'Kipas Angin', 'Pendingin Ruangan', 'Televisi', 'Remot Televisi', 'Setrika',
      'Mesin Cuci', 'Penyedot Debu', 'Lampu Belajar', 'Saklar Lampu', 'Stop Kontak',
      'Kabel Listrik', 'Senter', 'Baterai', 'Jam Dinding', 'Jam Tangan',
      'Kalender', 'Telepon Genggam', 'Charger', 'Laptop', 'Papan Ketik',
      'Tetikus', 'Printer', 'Speaker', 'Headset', 'Kamera',
      'Radio', 'Kasur', 'Bantal', 'Guling', 'Selimut',
      'Sprei', 'Kelambu', 'Lemari Pakaian', 'Gantungan Baju', 'Meja Belajar',
      'Kursi', 'Sofa', 'Karpet', 'Gorden', 'Kipas Tangan',
      'Pensil', 'Pulpen', 'Penghapus', 'Penggaris', 'Rautan Pensil',
      'Spidol', 'Buku Tulis', 'Kertas', 'Amplop', 'Lem Kertas',
      'Gunting', 'Stapler', 'Klip Kertas', 'Tas Sekolah', 'Kotak Pensil',
      'Papan Tulis', 'Kapur Tulis', 'Palu', 'Obeng', 'Tang',
      'Gergaji', 'Paku', 'Kunci Inggris', 'Meteran', 'Tangga Lipat',
      'Payung', 'Dompet', 'Kunci Rumah', 'Kacamata', 'Sandal Jepit',
    ],
  },
  {
    id: 'makanan',
    label: 'Makanan & Minuman',
    words: [
      'Nasi Goreng', 'Nasi Uduk', 'Nasi Kuning', 'Nasi Padang', 'Nasi Liwet',
      'Bubur Ayam', 'Lontong Sayur', 'Ketupat', 'Soto Ayam', 'Soto Betawi',
      'Rawon', 'Sop Buntut', 'Bakso', 'Mie Ayam', 'Mie Goreng',
      'Kwetiau Goreng', 'Bihun Goreng', 'Mie Rebus', 'Rendang', 'Gulai Kambing',
      'Sate Ayam', 'Sate Padang', 'Sate Kambing', 'Ayam Goreng', 'Ayam Bakar',
      'Ayam Geprek', 'Bebek Goreng', 'Ikan Bakar', 'Pepes Ikan', 'Pindang',
      'Cumi Goreng Tepung', 'Udang Balado', 'Telur Balado', 'Telur Dadar', 'Tempe Goreng',
      'Tahu Goreng', 'Tahu Isi', 'Oncom', 'Sayur Asem', 'Sayur Lodeh',
      'Sayur Bayam', 'Capcay', 'Tumis Kangkung', 'Gado-Gado', 'Karedok',
      'Pecel', 'Ketoprak', 'Lotek', 'Rujak Buah', 'Asinan Betawi',
      'Urap', 'Sambal Terasi', 'Kerupuk Udang', 'Emping', 'Rempeyek',
      'Abon Sapi', 'Dendeng Balado', 'Semur Jengkol', 'Pempek', 'Tekwan',
      'Siomay', 'Batagor', 'Bakwan Sayur', 'Risoles', 'Lumpia',
      'Martabak Manis', 'Martabak Telur', 'Pisang Goreng', 'Singkong Goreng', 'Ubi Rebus',
      'Jagung Bakar', 'Kacang Rebus', 'Kacang Goreng', 'Combro', 'Cireng',
      'Cilok', 'Cimol', 'Seblak', 'Telur Gulung', 'Sosis Bakar',
      'Roti Bakar', 'Klepon', 'Onde-Onde', 'Getuk', 'Lemper',
      'Nagasari', 'Kue Lapis', 'Kue Putu', 'Serabi', 'Bika Ambon',
      'Dadar Gulung', 'Wajik', 'Dodol', 'Bolu Kukus', 'Kue Cubit',
      'Putu Ayu', 'Apem', 'Lupis', 'Cenil', 'Wingko Babat',
      'Es Cendol', 'Es Doger', 'Es Teler', 'Es Campur', 'Es Kelapa Muda',
      'Es Teh Manis', 'Es Jeruk', 'Kopi Tubruk', 'Kopi Susu', 'Teh Tarik',
      'Wedang Jahe', 'Bandrek', 'Bajigur', 'Susu Kedelai', 'Jus Alpukat',
      'Jamu Kunyit Asam', 'Pizza', 'Burger', 'Spageti', 'Donat',
    ],
  },
  {
    id: 'hewan',
    label: 'Hewan',
    words: [
      'Kucing', 'Anjing', 'Sapi', 'Kerbau', 'Kambing',
      'Domba', 'Kuda', 'Babi', 'Ayam Jago', 'Bebek',
      'Angsa', 'Kelinci', 'Tikus', 'Hamster', 'Marmut',
      'Musang', 'Tupai', 'Landak', 'Kelelawar', 'Monyet',
      'Orangutan', 'Cacing Tanah', 'Bekantan', 'Tarsius', 'Harimau',
      'Singa', 'Macan Tutul', 'Beruang Madu', 'Gajah', 'Badak Bercula Satu',
      'Banteng', 'Rusa', 'Kijang', 'Anoa', 'Babirusa',
      'Trenggiling', 'Komodo', 'Buaya', 'Biawak', 'Ular Kobra',
      'Ular Piton', 'Kadal', 'Cicak', 'Tokek', 'Bunglon',
      'Iguana', 'Kura-Kura', 'Penyu', 'Katak', 'Kecoak',
      'Jangkrik', 'Jerapah', 'Zebra', 'Kuda Nil', 'Unta',
      'Panda', 'Koala', 'Kanguru', 'Serigala', 'Rubah',
      'Beruang Kutub', 'Pinguin', 'Anjing Laut', 'Walrus', 'Rakun',
      'Kukang', 'Sigung', 'Berang-Berang', 'Kelabang', 'Burung Merpati',
      'Burung Hantu', 'Elang', 'Rajawali', 'Kakatua', 'Nuri',
      'Beo', 'Jalak Bali', 'Cendrawasih', 'Merak', 'Kasuari',
      'Maleo', 'Pelikan', 'Bangau', 'Flamingo', 'Camar',
      'Pipit', 'Kutilang', 'Perkutut', 'Kolibri', 'Burung Unta',
      'Ayam Kalkun', 'Ikan Lele', 'Ikan Mas', 'Ikan Nila', 'Ikan Gurame',
      'Ikan Cupang', 'Ikan Arwana', 'Ikan Badut', 'Ikan Pari', 'Hiu',
      'Paus Biru', 'Lumba-Lumba', 'Gurita', 'Cumi-Cumi', 'Ubur-Ubur',
      'Bintang Laut', 'Kepiting', 'Rajungan', 'Udang Lobster', 'Kerang',
      'Kuda Laut', 'Belut', 'Semut', 'Lebah', 'Kupu-Kupu',
      'Nyamuk', 'Lalat', 'Capung', 'Belalang', 'Laba-Laba',
    ],
  },
  {
    id: 'profesi',
    label: 'Profesi & Tempat',
    words: [
      'Tukang Bakso', 'Tukang Parkir', 'Masinis', 'Pramugari', 'Pilot',
      'Dokter Gigi', 'Perawat', 'Bidan', 'Apoteker', 'Guru Ngaji',
      'Kepala Sekolah', 'Dosen', 'Polisi Lalu Lintas', 'Tentara', 'Satpam',
      'Tukang Ojek', 'Sopir Angkot', 'Kondektur', 'Kernet', 'Nelayan',
      'Petani', 'Peternak Ayam', 'Tukang Kebun', 'Tukang Cukur', 'Tukang Jahit',
      'Tukang Sol Sepatu', 'Tukang Pos', 'Tukang Sampah', 'Tukang Batu', 'Tukang Kayu',
      'Tukang Las', 'Tukang Listrik', 'Tukang Ledeng', 'Pedagang Asongan', 'Penjual Es Krim',
      'Koki', 'Pelayan Restoran', 'Barista', 'Kasir', 'Pramuniaga',
      'Kurir Paket', 'Petugas Kebersihan', 'Resepsionis', 'Sekretaris', 'Akuntan',
      'Pengacara', 'Hakim', 'Jaksa', 'Notaris', 'Wartawan',
      'Fotografer', 'Penyiar Radio', 'Pembawa Acara', 'Sutradara', 'Penyanyi Dangdut',
      'Pelawak', 'Dalang', 'Penari', 'Pelukis', 'Penulis Novel',
      'Arsitek', 'Programmer', 'Desainer Grafis', 'Montir', 'Pengrajin Batik',
      'Nakhoda', 'Pawang Hujan', 'Ustaz', 'Pendeta', 'Penghulu',
      'Lurah', 'Kepala Desa', 'Gubernur', 'Bupati', 'Presiden',
      'Menteri', 'Duta Besar', 'Pesepak Bola', 'Wasit', 'Pemandu Wisata',
      'Tukang Becak', 'Kusir Delman', 'Penjual Jamu Gendong', 'Petugas Pemadam Kebakaran',
      'Atlet Bulu Tangkis',
      'Puskesmas', 'Kantor Pos', 'Terminal Bus', 'Alun-Alun', 'Stasiun Kereta',
      'Pelabuhan', 'Bandara', 'Bengkel', 'Warteg', 'Pasar Malam',
      'Kebun Binatang', 'Masjid', 'Gereja', 'Pura', 'Kelenteng',
      'Rumah Sakit', 'Sekolah Dasar', 'Perpustakaan', 'Museum', 'Kantor Polisi',
      'Pos Ronda', 'Balai Desa', 'Pasar Tradisional', 'Bioskop', 'Warung Kopi',
      'Rumah Makan Padang', 'Panti Asuhan', 'Penjara', 'Pengadilan', 'Pegadaian',
      'Pom Bensin', 'Pesantren', 'Kolam Renang', 'Kebun Teh', 'Jembatan Layang',
    ],
  },
  {
    id: 'negara',
    label: 'Nama Negara',
    words: [
      'Indonesia', 'Malaysia', 'Singapura', 'Thailand', 'Vietnam',
      'Filipina', 'Myanmar', 'Kamboja', 'Laos', 'Brunei Darussalam',
      'Timor Leste', 'Tiongkok', 'Jepang', 'Korea Selatan', 'Korea Utara',
      'India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 'Nepal',
      'Afghanistan', 'Iran', 'Irak', 'Turki', 'Arab Saudi',
      'Uni Emirat Arab', 'Qatar', 'Kuwait', 'Yordania', 'Lebanon',
      'Suriah', 'Israel', 'Palestina', 'Yaman', 'Oman',
      'Mesir', 'Libya', 'Tunisia', 'Aljazair', 'Maroko',
      'Sudan', 'Ethiopia', 'Kenya', 'Tanzania', 'Uganda',
      'Nigeria', 'Ghana', 'Senegal', 'Kamerun', 'Pantai Gading',
      'Afrika Selatan', 'Zimbabwe', 'Mozambik', 'Madagaskar', 'Angola',
      'Rusia', 'Ukraina', 'Belarus', 'Polandia', 'Jerman',
      'Prancis', 'Inggris', 'Irlandia', 'Belanda', 'Belgia',
      'Luksemburg', 'Swiss', 'Austria', 'Italia', 'Spanyol',
      'Portugal', 'Yunani', 'Ceko', 'Slowakia', 'Hungaria',
      'Rumania', 'Bulgaria', 'Serbia', 'Kroasia', 'Albania',
      'Swedia', 'Norwegia', 'Denmark', 'Finlandia', 'Islandia',
      'Amerika Serikat', 'Kanada', 'Meksiko', 'Kuba', 'Brasil',
      'Argentina', 'Cile', 'Peru', 'Kolombia', 'Venezuela',
      'Australia', 'Selandia Baru', 'Papua Nugini', 'Fiji', 'Ekuador',
    ],
  },
  {
    id: 'ibukota',
    label: 'Nama Ibu Kota',
    words: [
      'Jakarta', 'Kuala Lumpur', 'Bangkok', 'Hanoi', 'Manila',
      'Naypyidaw', 'Phnom Penh', 'Vientiane', 'Bandar Seri Begawan', 'Dili',
      'Beijing', 'Tokyo', 'Seoul', 'Pyongyang', 'New Delhi',
      'Islamabad', 'Dhaka', 'Kolombo', 'Kathmandu', 'Kabul',
      'Teheran', 'Bagdad', 'Ankara', 'Riyadh', 'Abu Dhabi',
      'Doha', 'Amman', 'Beirut', 'Damaskus', 'Yerusalem',
      'Muskat', 'Manama', 'Kairo', 'Tripoli', 'Tunis',
      'Aljir', 'Rabat', 'Khartoum', 'Addis Ababa', 'Nairobi',
      'Dodoma', 'Kampala', 'Abuja', 'Accra', 'Dakar',
      'Yaounde', 'Pretoria', 'Harare', 'Maputo', 'Antananarivo',
      'Luanda', 'Kinshasa', 'Moskow', 'Kyiv', 'Minsk',
      'Warsawa', 'Berlin', 'Paris', 'London', 'Dublin',
      'Amsterdam', 'Brussel', 'Bern', 'Wina', 'Roma',
      'Madrid', 'Lisbon', 'Athena', 'Praha', 'Bratislava',
      'Budapest', 'Bukares', 'Sofia', 'Beograd', 'Zagreb',
      'Sarajevo', 'Tirana', 'Stockholm', 'Oslo', 'Kopenhagen',
      'Helsinki', 'Reykjavik', 'Washington', 'Ottawa', 'Kota Meksiko',
      'Havana', 'Brasilia', 'Buenos Aires', 'Santiago', 'Lima',
      'Bogota', 'Caracas', 'Canberra', 'Wellington', 'Port Moresby',
      'Suva', 'Quito', 'Montevideo', 'Asuncion', 'La Paz',
    ],
  },
  {
    id: 'kota',
    label: 'Nama Kota di Indonesia',
    words: [
      'Banda Aceh', 'Lhokseumawe', 'Sabang', 'Medan', 'Binjai',
      'Pematangsiantar', 'Tebing Tinggi', 'Sibolga', 'Padangsidimpuan', 'Padang',
      'Bukittinggi', 'Payakumbuh', 'Pariaman', 'Solok', 'Pekanbaru',
      'Dumai', 'Tanjungpinang', 'Batam', 'Jambi', 'Palembang',
      'Lubuklinggau', 'Prabumulih', 'Bengkulu', 'Bandar Lampung', 'Metro',
      'Pangkalpinang', 'Bandung', 'Bogor', 'Depok', 'Bekasi',
      'Cimahi', 'Sukabumi', 'Tasikmalaya', 'Cirebon', 'Garut',
      'Banjar', 'Serang', 'Cilegon', 'Tangerang', 'Semarang',
      'Surakarta', 'Salatiga', 'Magelang', 'Pekalongan', 'Tegal',
      'Kudus', 'Purwokerto', 'Yogyakarta', 'Bantul', 'Sleman',
      'Surabaya', 'Malang', 'Batu', 'Kediri', 'Blitar',
      'Madiun', 'Mojokerto', 'Pasuruan', 'Probolinggo', 'Jember',
      'Banyuwangi', 'Sidoarjo', 'Gresik', 'Bojonegoro', 'Pamekasan',
      'Sumenep', 'Pontianak', 'Singkawang', 'Palangkaraya', 'Sampit',
      'Banjarmasin', 'Banjarbaru', 'Balikpapan', 'Samarinda', 'Bontang',
      'Tarakan', 'Nunukan', 'Ketapang', 'Tanjung Selor', 'Makassar',
      'Parepare', 'Palopo', 'Manado', 'Bitung', 'Tomohon',
      'Kotamobagu', 'Gorontalo', 'Palu', 'Poso', 'Kendari',
      'Baubau', 'Mamuju', 'Tana Toraja', 'Bulukumba', 'Denpasar',
      'Badung', 'Gianyar', 'Singaraja', 'Tabanan', 'Klungkung',
      'Mataram', 'Bima', 'Sumbawa Besar', 'Kupang', 'Ende',
      'Maumere', 'Labuan Bajo', 'Waingapu', 'Atambua', 'Ambon',
      'Tual', 'Ternate', 'Tidore', 'Sofifi', 'Jayapura',
      'Sorong', 'Manokwari', 'Merauke', 'Timika', 'Wamena',
    ],
  },
]

export const ALL_CATEGORY_IDS: CategoryId[] = CATEGORIES.map((c) => c.id)

/**
 * Bangun tumpukan kartu dari kategori yang dipilih. Dipanggil sekali per sesi.
 * "Campur Semua" = kirim semua id kategori.
 */
export function buildCards(selected: CategoryId[]): Card[] {
  const wanted = new Set(selected)
  return CATEGORIES.filter((c) => wanted.has(c.id)).flatMap((c) =>
    c.words.map((text) => ({
      id: `${c.id}:${text}`,
      text,
      categoryId: c.id,
    })),
  )
}
